### ISSUE TITLE
No editor appears with `any_of`

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/shacl-vue#127]
https://annotate.inm7.de/s/data/?sh%3ANodeShape=inm7fd%3ADistribution&edit=true

The underlying range is

```yaml
    slot_usage:
      distribution_of:
        required: true
        any_of:
          - range: Dataset
          - range: DataItem
```
